#!/usr/bin/env python3
"""Command-line interface for ssys recasting tool."""

import argparse
import os
import sys

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

import ssys
from ssys import parse_antimony, build_sym_system, recast_to_ssystem, ssystem_to_antimony


def read_manifest(path: str) -> list[str]:
    """Read a manifest file and return list of absolute paths to .ant files."""
    items = []
    with open(path, "r") as f:
        for ln in f:
            s = ln.strip()
            if not s or s.startswith("#"):
                continue
            items.append(os.path.abspath(s))
    return items


def recast_file(ant_path: str, out_dir: str, mode: str = "simplified") -> tuple[str, str, str]:
    """
    Recast a single Antimony file to S-system form.

    Args:
        ant_path: Path to input Antimony file
        out_dir: Output directory for recast file
        mode: Output mode ('simplified' or 'canonical')

    Returns:
        Tuple of (model_name, input_path, output_path)
    """
    name = os.path.splitext(os.path.basename(ant_path))[0]
    txt = open(ant_path).read()

    ir = parse_antimony(txt)
    sym = build_sym_system(ir)
    rec = recast_to_ssystem(sym, mode=mode)
    out_text = ssystem_to_antimony(rec, model_name=f"{name}_recast", mode=mode)

    out_path = os.path.join(out_dir, f"{name}_recast.ant")
    with open(out_path, "w") as f:
        f.write(out_text)

    return name, ant_path, out_path


def build_notebook(cases: list[tuple[str, str, str]], out_dir: str,
                    mode: str = "simplified") -> str:
    """
    Build a Jupyter notebook that reports on all recast models.

    Args:
        cases: List of (model_name, input_path, output_path) tuples
        out_dir: Output directory for notebook
        mode: Output mode ('simplified' or 'canonical')

    Returns:
        Path to generated notebook
    """
    nb = new_notebook()
    nb.cells.append(
        new_markdown_cell("# ODE → S-System Recaster Report\nGenerated by ssys CLI")
    )

    # Simple import cell - imports from the notebook_helpers module
    helpers = '''import os
import sys
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from IPython.display import display, Markdown, Code

import ssys
from ssys.notebook_helpers import load_and_report
'''
    nb.cells.append(new_code_cell(helpers))

    # One code cell per case
    for name, ant_path, recast_path in cases:
        nb.cells.append(new_markdown_cell(f"## {name}"))
        # Make recast path relative to notebook location (basename only)
        recast_basename = os.path.basename(recast_path)
        call = (f"load_and_report({repr(ant_path)}, "
                f"{repr(recast_basename)}, mode={repr(mode)})")
        nb.cells.append(new_code_cell(call))

    out_nb = os.path.join(out_dir, "recast_report.ipynb")
    with open(out_nb, "w") as f:
        nbformat.write(nb, f)
    return out_nb


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Recast Antimony models to canonical S-system form.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Plain-text file: one .ant path per line.",
    )
    parser.add_argument(
        "--outdir",
        required=True,
        help="Output directory for recast .ant files and the notebook.",
    )
    parser.add_argument(
        "--mode",
        choices=["simplified", "canonical"],
        default="simplified",
        help="Output mode: 'simplified' (default, current behavior) or 'canonical' (strict 2-term S-system form)",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {ssys.__version__}",
    )
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    ant_files = read_manifest(args.manifest)
    if not ant_files:
        print("Error: Manifest contained no .ant files.", file=sys.stderr)
        sys.exit(1)

    print(f"Processing {len(ant_files)} model(s)...")
    cases = [recast_file(ant, args.outdir, mode=args.mode)
             for ant in ant_files]

    nb_path = build_notebook(cases, args.outdir, mode=args.mode)
    print(f"✓ Recast complete. Notebook written: {nb_path}")


if __name__ == "__main__":
    main()
