#!/usr/bin/env python3
"""Command-line interface for ssys recasting tool."""

import argparse
import os
import sys

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

import ssys
from ssys import parse_antimony, build_sym_system, recast_to_ssystem, ssystem_to_antimony


def read_manifest(path: str) -> list[str]:
    """Read a manifest file and return list of absolute paths to .ant files."""
    items = []
    with open(path, "r") as f:
        for ln in f:
            s = ln.strip()
            if not s or s.startswith("#"):
                continue
            items.append(os.path.abspath(s))
    return items


def recast_file(ant_path: str, out_dir: str) -> tuple[str, str, str]:
    """
    Recast a single Antimony file to S-system form.

    Args:
        ant_path: Path to input Antimony file
        out_dir: Output directory for recast file

    Returns:
        Tuple of (model_name, input_path, output_path)
    """
    name = os.path.splitext(os.path.basename(ant_path))[0]
    txt = open(ant_path).read()

    ir = parse_antimony(txt)
    sym = build_sym_system(ir)
    rec = recast_to_ssystem(sym)
    out_text = ssystem_to_antimony(rec, model_name=f"{name}_recast")

    out_path = os.path.join(out_dir, f"{name}_recast.ant")
    with open(out_path, "w") as f:
        f.write(out_text)

    return name, ant_path, out_path


def build_notebook(cases: list[tuple[str, str, str]], out_dir: str) -> str:
    """
    Build a Jupyter notebook that reports on all recast models.

    Args:
        cases: List of (model_name, input_path, output_path) tuples
        out_dir: Output directory for notebook

    Returns:
        Path to generated notebook
    """
    nb = new_notebook()
    nb.cells.append(
        new_markdown_cell("# ODE → S-System Recaster Report\nGenerated by ssys CLI")
    )

    helpers = r'''
# --- start helpers cell ---
import os
import sys
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from IPython.display import display, Markdown, Code

import ssys

FILL_MISSING_PARAMS = False  # set True to auto-fill absent params with 1.0


def rk4(f, t_span, y0, n_steps):
    """Simple RK4 integrator."""
    t0, t1 = t_span
    t = np.linspace(t0, t1, n_steps+1)
    h = (t1 - t0) / n_steps
    y = np.zeros((len(t), len(y0)), dtype=float)
    y[0] = np.array(y0, dtype=float)
    for i in range(n_steps):
        ti = t[i]
        yi = y[i]
        k1 = f(ti, yi)
        k2 = f(ti + 0.5*h, yi + 0.5*h*k1)
        k3 = f(ti + 0.5*h, yi + 0.5*h*k2)
        k4 = f(ti + h, yi + h*k3)
        y[i+1] = yi + (h/6.0)*(k1 + 2*k2 + 2*k3 + k4)
    return t, y


def build_rhs_from_sympy(vars_syms, rhs_exprs, param_vals):
    """Build numerical RHS function from symbolic expressions."""
    var_set = set(vars_syms)
    rhs_free = set().union(*[expr.free_symbols for expr in rhs_exprs])

    param_subs = {}
    missing = []
    for s in sorted(rhs_free - var_set, key=lambda z: z.name):
        name = s.name
        if name in param_vals:
            param_subs[s] = float(param_vals[name])
        else:
            missing.append(name)

    if missing and not FILL_MISSING_PARAMS:
        raise ValueError("Missing numeric values for parameters: " + ", ".join(sorted(set(missing))))
    if missing and FILL_MISSING_PARAMS:
        for sname in set(missing):
            sym = next(ss for ss in rhs_free if ss.name == sname and ss not in var_set)
            param_subs[sym] = 1.0
        display(Markdown("> **Warning**: filled missing params with 1.0 → " + ", ".join(sorted(set(missing)))))

    def f(t, y):
        subs = {s: float(y[i]) for i, s in enumerate(vars_syms)}
        subs.update(param_subs)
        vals = [float(expr.evalf(subs=subs)) for expr in rhs_exprs]
        return np.array(vals, dtype=float)
    return f


def _expand_exps_through_factors(exps, factor_map):
    """Expand exponents through factor map."""
    new = {}
    for s, e in exps.items():
        if s in factor_map:
            for v in factor_map[s]:
                new[v] = new.get(v, 0.0) + float(e)
        else:
            new[s] = new.get(s, 0.0) + float(e)
    return new


def product_expr(coeff, exps):
    """Build symbolic product expression from coefficient and exponents."""
    expr = sp.Float(coeff)
    for s, e in sorted(exps.items(), key=lambda kv: kv[0].name):
        expr *= s**sp.Float(e)
    return sp.simplify(expr)


def latex_odes_from_sym(sym):
    """Generate LaTeX for original ODEs."""
    lines = []
    for v in sorted(sym.odes.keys(), key=lambda s: s.name):
        rhs = sp.simplify(sym.odes[v])
        lines.append(r"\dot{%s} &= %s" % (sp.latex(v), sp.latex(rhs)))
    return "\\begin{aligned}\n" + " \\\\\n".join(lines) + "\n\\end{aligned}"


def latex_ssys_from_rec(rec):
    """Generate LaTeX for recast S-system."""
    rows = []
    for eq in rec.equations:
        g = product_expr(eq.growth[0], _expand_exps_through_factors(eq.growth[1], rec.factor_map))
        d = product_expr(eq.decay[0], _expand_exps_through_factors(eq.decay[1], rec.factor_map))
        rows.append(r"\dot{%s} &= %s - %s" % (sp.latex(eq.var), sp.latex(g), sp.latex(d)))
    return "\\begin{aligned}\n" + " \\\\\n".join(rows) + "\n\\end{aligned}"


def latex_factor_map(rec):
    """Generate LaTeX for factor mapping."""
    rows = []
    for orig, aux_list in sorted(rec.factor_map.items(), key=lambda kv: kv[0].name):
        left = sp.latex(orig)
        right = " \\cdot ".join(sp.latex(a) for a in aux_list) if aux_list else "1"
        rows.append(f"{left} &= {right}")
    return "\\begin{aligned}\n" + " \\\\\n".join(rows) + "\n\\end{aligned}"


def max_recast_residual(sym, rec, params):
    """Compute maximum relative residual to verify exactness."""
    var_syms = sorted(sym.odes.keys(), key=lambda s: s.name)
    rhs_exprs = [sp.simplify(sym.odes[s]) for s in var_syms]
    par_syms = [sp.Symbol(k) for k in params.keys()]
    rhs_fun = sp.lambdify(var_syms + par_syms, rhs_exprs, "numpy")

    aux_syms = list(sorted(rec.variables, key=lambda s: s.name))
    aux_idx = {s: i for i, s in enumerate(aux_syms)}

    def Vj_rhs_funcs():
        funs = {}
        for eq in rec.equations:
            g = product_expr(eq.growth[0], _expand_exps_through_factors(eq.growth[1], rec.factor_map))
            d = product_expr(eq.decay[0], _expand_exps_through_factors(eq.decay[1], rec.factor_map))
            funs[eq.var] = sp.lambdify(aux_syms + par_syms, sp.simplify(g - d), "numpy")
        return funs

    vdot = Vj_rhs_funcs()
    rng = np.random.default_rng(0)
    max_rel = 0.0
    for _ in range(5):
        V = 10**rng.uniform(-2, 2, size=len(aux_syms))
        Xvals = {}
        for X in var_syms:
            prod = 1.0
            for a in rec.factor_map[X]:
                prod *= V[aux_idx[a]]
            Xvals[X] = prod
        rhs = np.array(rhs_fun(*[Xvals[s] for s in var_syms], *[params[k] for k in params]), dtype=float)

        Xdot_rec = np.zeros_like(rhs, dtype=float)
        for i, X in enumerate(var_syms):
            ssum = 0.0
            for a in rec.factor_map[X]:
                others = 1.0
                for b in rec.factor_map[X]:
                    if b != a:
                        others *= V[aux_idx[b]]
                ssum += vdot[a](*V, *[params[k] for k in params]) * others
            Xdot_rec[i] = float(ssum)
        denom = np.maximum(1e-12, np.abs(rhs))
        max_rel = max(max_rel, np.max(np.abs(Xdot_rec - rhs) / denom))
    return max_rel


def load_and_report(ant_path, recast_path, T=20.0, steps=400):
    """Load and report on a single recast model."""
    ant_text = open(ant_path).read()
    rec_text = open(recast_path).read()
    display(Markdown("**Files**"))
    display(Markdown(f"- Antimony input: `{os.path.basename(ant_path)}`<br>- Recast output: `{os.path.basename(recast_path)}`"))
    display(Markdown("**Original Antimony**"))
    display(Code(ant_text, language="text"))
    display(Markdown("**Recast Antimony**"))
    display(Code(rec_text, language="text"))

    ir = ssys.parse_antimony(ant_text)
    sym = ssys.build_sym_system(ir)
    rec = ssys.recast_to_ssystem(sym)

    params = dict(sym.params)
    resid = max_recast_residual(sym, rec, params)
    display(Markdown(f"**Algebraic residual (should be ~0):** `{resid:.2e}`"))

    display(Markdown("**Mapping (original -> product of auxiliaries)**"))
    display(Markdown("$$\n" + latex_factor_map(rec) + "\n$$"))

    display(Markdown("**Original ODEs (LaTeX)**"))
    display(Markdown("$$\n" + latex_odes_from_sym(sym) + "\n$$"))
    display(Markdown("**Recast S-System ODEs (LaTeX)**"))
    display(Markdown("$$\n" + latex_ssys_from_rec(rec) + "\n$$"))

    # Integrate original
    var_syms = sorted(sym.odes.keys(), key=lambda s: s.name)
    rhs_exprs = [sp.simplify(sym.odes[s]) for s in var_syms]
    y0 = [float(sym.initials[s]) for s in var_syms]
    f_orig = build_rhs_from_sympy(var_syms, rhs_exprs, params)
    t_orig, y_orig = rk4(f_orig, (0.0, T), y0, steps)

    # Integrate recast
    aux_syms = list(sorted(rec.variables, key=lambda s: s.name))
    rec_rhs = [
        sp.simplify(
            product_expr(eq.growth[0], _expand_exps_through_factors(eq.growth[1], rec.factor_map)) -
            product_expr(eq.decay[0], _expand_exps_through_factors(eq.decay[1], rec.factor_map))
        )
        for eq in rec.equations
    ]
    aux_y0 = [float(rec.initials[s]) for s in aux_syms]
    f_rec = build_rhs_from_sympy(aux_syms, rec_rhs, params)
    t_rec, y_rec = rk4(f_rec, (0.0, T), aux_y0, steps)

    # Plot comparison
    fig, axes = plt.subplots(1, 2, figsize=(9, 3), dpi=120, sharey=True)

    ax = axes[0]
    for i, s in enumerate(var_syms):
        ax.plot(t_orig, y_orig[:, i], label=str(s))
    ax.set_title("Original system", fontsize=10)
    ax.set_xlabel("t", fontsize=9)
    ax.set_ylabel("state", fontsize=9)
    ax.legend(fontsize=8, loc="best")
    ax.tick_params(labelsize=8)

    ax = axes[1]
    aux_idx = {s: i for i, s in enumerate(aux_syms)}
    for k, factors in sorted(rec.factor_map.items(), key=lambda kv: kv[0].name):
        prod = np.ones(y_rec.shape[0], dtype=float)
        for s in factors:
            prod *= y_rec[:, aux_idx[s]]
        ax.plot(t_rec, prod, label=str(k))
    ax.set_title("Reconstructed from recast", fontsize=10)
    ax.set_xlabel("t", fontsize=9)
    ax.set_ylabel("state", fontsize=9)
    ax.legend(fontsize=8, loc="best")
    ax.tick_params(labelsize=8)

    fig.tight_layout()
# --- end helpers cell ---
'''
    nb.cells.append(new_code_cell(helpers))

    # One code cell per case
    for name, ant_path, recast_path in cases:
        nb.cells.append(new_markdown_cell(f"## {name}"))
        call = f"load_and_report({repr(ant_path)}, {repr(recast_path)})"
        nb.cells.append(new_code_cell(call))

    out_nb = os.path.join(out_dir, "recast_report.ipynb")
    with open(out_nb, "w") as f:
        nbformat.write(nb, f)
    return out_nb


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Recast Antimony models to canonical S-system form.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Plain-text file: one .ant path per line.",
    )
    parser.add_argument(
        "--outdir",
        required=True,
        help="Output directory for recast .ant files and the notebook.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {ssys.__version__}",
    )
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    ant_files = read_manifest(args.manifest)
    if not ant_files:
        print("Error: Manifest contained no .ant files.", file=sys.stderr)
        sys.exit(1)

    print(f"Processing {len(ant_files)} model(s)...")
    cases = [recast_file(ant, args.outdir) for ant in ant_files]

    nb_path = build_notebook(cases, args.outdir)
    print(f"✓ Recast complete. Notebook written: {nb_path}")


if __name__ == "__main__":
    main()
