#!/usr/bin/env python3
"""
Validate existing recasts against their original SBML files.

Runs validation on recasts produced by 3_recast_batch.py.
This allows recasting and validation to be run as separate phases.

Three-Stage Validation Pipeline:
Stage 1 (fast, robust):
    python 3b_validate_batch.py --numerical-only --timeout 60 --workers 8

Stage 2 (JAX cross-check on passed models):
    python 3b_validate_batch.py --numerical-only --use-jax --passed-only \
        --timeout 120 --workers 8

Stage 3 (symbolic proof on passed models, subprocess isolation):
    python 3b_validate_batch.py --symbolic-only --passed-only --subprocess \
        --timeout 120 --workers 4

Usage:
    # Validate all existing recasts
    python 3b_validate_batch.py

    # Validate specific mode
    python 3b_validate_batch.py --mode simplified

    # Limit number of models
    python 3b_validate_batch.py --limit 10

    # Skip models already validated
    python 3b_validate_batch.py --resume

    # Only validate models that passed numerical validation
    python 3b_validate_batch.py --passed-only --symbolic-only

Output:
    results/validation/ - Validation JSON reports
    results/validation_summary.txt - Summary statistics
"""

import argparse
import json
import logging
import multiprocessing as mp
import os
import queue
import sys
import tempfile
import time
import warnings
from pathlib import Path

import antimony
import numpy as np

# Suppress NumPy warnings about invalid values (e.g., negative^fractional)
# These occur during lambdified function evaluation and are handled by
# detecting NaN in the results.
warnings.filterwarnings("ignore", category=RuntimeWarning, module="numpy")
np.seterr(invalid="ignore", divide="ignore")

# Add parent directory to path for ssys import
sys.path.insert(0, str(Path(__file__).parent.parent))

import config  # noqa: E402
import utils  # noqa: E402

from ssys._validator.numerical import NUMERICAL_SAMPLE_EVALUATION_TIMEOUT_SECONDS  # noqa: E402
from ssys.validator import VALIDATION_REPORT_SCHEMA_VERSION, validate_recast_pair  # noqa: E402

logger = logging.getLogger(__name__)


def _test_result(
    name: str,
    result: str,
    reason: str | None,
    details: str,
    metadata: dict | None = None,
) -> dict:
    """Return a schema-shaped validation test result."""
    return {
        "name": name,
        "result": result,
        "reason": reason,
        "max_error": None,
        "mean_error": None,
        "details": details,
        "counterexamples": [],
        "metadata": metadata or {},
    }


def _profile_for_flags(
    *,
    symbolic_only: bool,
    numerical_only: bool,
) -> tuple[str, str, list[str]]:
    """Return validation-profile metadata matching validate_model flags."""
    required = ["generated_output", "parser", "mapping"]
    if numerical_only:
        required.extend(["numerical", "auxiliaries"])
        return "custom", "BioModels numerical-only validation wrapper.", required
    if symbolic_only:
        required.extend(["symbolic", "auxiliaries"])
        return "custom", "BioModels symbolic-only validation wrapper.", required
    required.extend(["symbolic", "numerical", "trajectory", "algebraic_residuals", "auxiliaries"])
    return "custom", "BioModels full validation wrapper.", required


def _selected_failure_test(
    *,
    symbolic_only: bool,
    numerical_only: bool,
) -> str:
    if numerical_only:
        return "numerical"
    if symbolic_only:
        return "symbolic"
    return "parser"


def _wrapper_failure_reason(message: str) -> str:
    lowered = message.lower()
    if "codec can't decode" in lowered or "unicodedecodeerror" in lowered:
        return "input_decode_failed"
    if "failed to load sbml" in lowered:
        return "input_sbml_load_failed"
    if "timeout after" in lowered:
        return "validator_timeout"
    if "subprocess communication failed" in lowered:
        return "validator_subprocess_failed"
    return "validation_worker_failed"


def _is_wrapper_failure_report(report: dict) -> bool:
    """Return True for reports generated by this wrapper before validation completed."""
    wrapper_reasons = {
        "input_decode_failed",
        "input_load_failed",
        "input_sbml_load_failed",
        "validation_worker_failed",
        "validator_subprocess_failed",
        "validator_timeout",
    }
    for test in report.get("tests", {}).values():
        if isinstance(test, dict) and test.get("reason") in wrapper_reasons:
            return True
        if isinstance(test, list):
            for item in test:
                if isinstance(item, dict) and item.get("reason") in wrapper_reasons:
                    return True
    return False


def _validation_failure_report(
    *,
    model_id: str,
    mode: str,
    original_file: str,
    recast_file: str,
    details: str,
    symbolic_only: bool,
    numerical_only: bool,
    use_jax: bool,
    overall_result: str = "failed",
    reason: str | None = None,
    timeout_seconds: int | None = None,
    phase: str = "unknown",
    phase_history: list[dict] | None = None,
) -> dict:
    """Build a validation-report-shaped payload for wrapper-level failures."""
    reason = reason or _wrapper_failure_reason(details)
    profile_name, profile_description, required_tests = _profile_for_flags(
        symbolic_only=symbolic_only,
        numerical_only=numerical_only,
    )
    metadata = {
        "model_id": model_id,
        "mode": mode,
        "use_jax": use_jax,
        "validation_phase": phase,
    }
    if timeout_seconds is not None:
        metadata["timeout_seconds"] = timeout_seconds
    if phase_history:
        metadata["phase_history"] = phase_history
        phase_intervals = _phase_intervals_from_history(
            phase_history,
            final_elapsed_seconds=timeout_seconds if overall_result == "timeout" else None,
        )
        if phase_intervals:
            metadata["phase_intervals"] = phase_intervals
            dominant = _dominant_phase_interval(phase_intervals)
            if dominant is not None:
                metadata["dominant_phase_interval"] = dominant

    selected_result = overall_result
    selected_reason = reason
    selected_details = details
    selected_test = _selected_failure_test(
        symbolic_only=symbolic_only,
        numerical_only=numerical_only,
    )
    if reason == "validator_timeout" and phase.startswith("numerical_sample_evaluation"):
        selected_result = "not_attempted"
        selected_reason = "numerical_complexity"
        selected_test = "numerical"
        selected_details = (
            "Numerical sample evaluation exceeded complexity budget before the "
            f"BioModels wrapper returned: {details}"
        )
        overall_result = "not_attempted"
        phase_parts = phase.split(":", 2)
        active_subphase = phase_parts[1] if len(phase_parts) >= 2 else None
        active_label = phase_parts[2] if len(phase_parts) >= 3 else None
        diagnostic = {
            "side": "numerical",
            "reason": "numerical_complexity",
            "phase": "numerical_sample_evaluation",
            "active_subphase": active_subphase,
            "active_expression_label": active_label,
            "elapsed_seconds": timeout_seconds,
            "limit_seconds": NUMERICAL_SAMPLE_EVALUATION_TIMEOUT_SECONDS,
            "wrapper_timeout_seconds": timeout_seconds,
            "wrapper_timeout_phase": phase,
        }
        dominant = metadata.get("dominant_phase_interval")
        if isinstance(dominant, dict):
            diagnostic["dominant_phase_interval"] = dominant
        metadata.setdefault("diagnostics", []).append(diagnostic)

    tests = {
        "generated_output": _test_result(
            "generated_output_roundtrip",
            "not_attempted",
            "blocked_by_wrapper_failure",
            "Check did not run because the BioModels validation wrapper failed",
            metadata,
        ),
        "parser": _test_result(
            "validator_parser",
            "not_attempted",
            "blocked_by_wrapper_failure",
            "Check did not run because the BioModels validation wrapper failed",
            metadata,
        ),
        "mapping": _test_result(
            "mapping_completeness",
            "not_attempted",
            "blocked_by_wrapper_failure",
            "Check did not run because the BioModels validation wrapper failed",
            metadata,
        ),
        "symbolic": _test_result(
            "symbolic_equivalence",
            "not_attempted",
            "profile_excluded" if numerical_only else "blocked_by_wrapper_failure",
            "Check did not run because the BioModels validation wrapper failed",
            metadata,
        ),
        "numerical": _test_result(
            "numerical_pointwise_jax" if use_jax else "numerical_pointwise",
            "not_attempted",
            "profile_excluded" if symbolic_only else "blocked_by_wrapper_failure",
            "Check did not run because the BioModels validation wrapper failed",
            metadata,
        ),
        "trajectory": _test_result(
            "trajectory_comparison",
            "not_attempted",
            "profile_excluded",
            "Check is not part of this BioModels validation stage",
            metadata,
        ),
        "algebraic_residuals": _test_result(
            "algebraic_manifold_residuals",
            "not_attempted",
            "profile_excluded",
            "Check is not part of this BioModels validation stage",
            metadata,
        ),
        "auxiliaries": [
            _test_result(
                "auxiliary_identities",
                "not_attempted",
                "blocked_by_wrapper_failure",
                "Check did not run because the BioModels validation wrapper failed",
                metadata,
            )
        ],
    }
    tests[selected_test] = _test_result(
        {
            "numerical": "numerical_pointwise_jax" if use_jax else "numerical_pointwise",
            "symbolic": "symbolic_equivalence",
            "parser": "validator_parser",
        }[selected_test],
        selected_result,
        selected_reason,
        selected_details,
        metadata,
    )

    return {
        "schema_version": VALIDATION_REPORT_SCHEMA_VERSION,
        "original_file": original_file,
        "recast_file": recast_file,
        "validation_profile": {
            "name": profile_name,
            "description": profile_description,
            "required_tests": required_tests,
        },
        "classification": {
            "original": None,
            "recast": None,
            "expected": "S-system" if mode == "simplified" else "Canonical S-system",
            "canonical_refusal_reason": None,
        },
        "solver": {
            "original_requirement": None,
            "recast_requirement": None,
        },
        "tests": tests,
        "overall_pass": False,
        "overall_result": overall_result,
        "summary": (
            "Validation TIMEOUT: BioModels wrapper exceeded its per-model limit"
            if overall_result == "timeout"
            else "Validation NOT ATTEMPTED: a required check was skipped"
            if overall_result == "not_attempted"
            else "Validation FAILED: BioModels wrapper failed before validation completed"
        ),
    }


def _record_validation_phase(
    phase_queue,
    phase: str,
    started_at: float,
) -> None:
    """Best-effort phase progress update for parent timeout diagnostics."""
    if phase_queue is None:
        return
    try:
        phase_queue.put({
            "phase": phase,
            "elapsed_seconds": round(time.monotonic() - started_at, 6),
        })
    except Exception:
        return


def _drain_phase_updates(phase_queue) -> tuple[str | None, list[dict]]:
    """Return the latest validation phase and all queued progress updates."""
    if phase_queue is None:
        return None, []

    history: list[dict] = []
    while True:
        try:
            update = phase_queue.get_nowait()
        except queue.Empty:
            break
        except Exception:
            break
        if isinstance(update, dict):
            history.append(update)

    latest = history[-1].get("phase") if history else None
    return str(latest) if latest else None, history


def _phase_intervals_from_history(
    phase_history: list[dict] | None,
    *,
    final_elapsed_seconds: float | int | None = None,
) -> list[dict]:
    """Derive phase intervals from phase-start history records."""
    if not phase_history:
        return []

    starts: list[tuple[str, float]] = []
    for item in phase_history:
        if not isinstance(item, dict) or not item.get("phase"):
            continue
        try:
            elapsed = float(item["elapsed_seconds"])
        except (KeyError, TypeError, ValueError):
            continue
        starts.append((str(item["phase"]), elapsed))

    intervals: list[dict] = []
    for (phase, start), (next_phase, end) in zip(starts, starts[1:]):
        if end < start:
            continue
        intervals.append({
            "phase": phase,
            "start_seconds": round(start, 6),
            "end_seconds": round(end, 6),
            "duration_seconds": round(end - start, 6),
            "next_phase": next_phase,
        })

    if final_elapsed_seconds is not None and starts:
        phase, start = starts[-1]
        try:
            final_elapsed = float(final_elapsed_seconds)
        except (TypeError, ValueError):
            final_elapsed = None
        if final_elapsed is not None and final_elapsed > start:
            intervals.append({
                "phase": phase,
                "start_seconds": round(start, 6),
                "end_seconds": round(final_elapsed, 6),
                "duration_seconds": round(final_elapsed - start, 6),
                "next_phase": "timeout_budget",
            })

    return intervals


def _dominant_phase_interval(phase_intervals: list[dict]) -> dict | None:
    """Return the longest phase interval, if one is available."""
    if not phase_intervals:
        return None
    return max(phase_intervals, key=lambda item: item.get("duration_seconds", 0.0))


def _attach_validation_timing_metadata(
    report: dict,
    *,
    phase: str,
    phase_history: list[dict] | None,
    timeout_seconds: int | None,
    final_elapsed_seconds: float | int | None = None,
) -> dict:
    """Attach BioModels wrapper timing metadata to schema-shaped test entries."""
    if not phase_history:
        return report

    phase_intervals = _phase_intervals_from_history(
        phase_history,
        final_elapsed_seconds=final_elapsed_seconds,
    )
    timing_metadata = {
        "validation_phase": phase,
        "phase_history": phase_history,
    }
    if timeout_seconds is not None:
        timing_metadata["timeout_seconds"] = timeout_seconds
    if phase_intervals:
        timing_metadata["phase_intervals"] = phase_intervals
        dominant = _dominant_phase_interval(phase_intervals)
        if dominant is not None:
            timing_metadata["dominant_phase_interval"] = dominant

    tests = report.get("tests", {})
    if not isinstance(tests, dict):
        return report

    def attach_to_test(test: dict) -> None:
        metadata = test.get("metadata")
        if not isinstance(metadata, dict):
            metadata = {}
        metadata.update(timing_metadata)
        test["metadata"] = metadata

    for test in tests.values():
        if isinstance(test, dict):
            attach_to_test(test)
        elif isinstance(test, list):
            for item in test:
                if isinstance(item, dict):
                    attach_to_test(item)
    return report


def find_recast_files(mode: str) -> list[tuple[str, Path, Path]]:
    """
    Find all recast files and their matching SBML originals.

    Returns:
        List of (model_id, sbml_path, recast_path) tuples
    """
    recasts_dir = Path(config.RECASTS_DIR)
    sbml_dir = Path(config.SBML_CANDIDATES_DIR)

    if not recasts_dir.exists():
        logger.error(f"Recasts directory not found: {recasts_dir}")
        return []

    pairs = []
    for recast_file in sorted(recasts_dir.glob(f"*_{mode}.ant")):
        # Extract model_id from filename: BIOMD0000000146_simplified.ant
        model_id = recast_file.stem.replace(f"_{mode}", "")

        # Find matching SBML
        sbml_path = sbml_dir / f"{model_id}.xml"
        if sbml_path.exists():
            pairs.append((model_id, sbml_path, recast_file))
        else:
            logger.warning(f"SBML not found for {model_id}")

    return pairs


def filter_passed_models(
    pairs: list[tuple[str, Path, Path]], mode: str
) -> list[tuple[str, Path, Path]]:
    """
    Filter to only models that passed numerical validation (Stage 1).

    Checks _numerical.json files for pass status.
    """
    filtered = []
    for model_id, sbml_path, recast_path in pairs:
        # Check Stage 1 numerical validation file
        val_path = Path(config.VALIDATION_DIR) / f"{model_id}_{mode}_numerical.json"
        if not val_path.exists():
            continue

        try:
            with open(val_path) as f:
                report = json.load(f)

            # Check if numerical test passed
            if report.get("overall_pass", False):
                filtered.append((model_id, sbml_path, recast_path))
        except Exception:
            continue

    return filtered


def validate_model(
    model_id: str, sbml_path: Path, recast_path: Path, mode: str,
    symbolic_only: bool = False, numerical_only: bool = False,
    use_jax: bool = False,
    phase_queue=None,
) -> dict:
    """
    Validate a single recast against its original SBML.

    Args:
        model_id: Model identifier
        sbml_path: Path to original SBML file
        recast_path: Path to recast Antimony file
        mode: Recast mode ('simplified' or 'canonical')
        symbolic_only: If True, only run symbolic test
        numerical_only: If True, only run numerical test (fast, no symbolic)
        use_jax: Use JAX autodiff for numerical validation

    Returns:
        Validation report dict
    """
    started_at = time.monotonic()
    phase_state = {"current": "input_load"}

    def set_phase(phase: str) -> None:
        phase_state["current"] = phase
        _record_validation_phase(phase_queue, phase, started_at)

    set_phase("input_load")

    try:
        # Convert SBML to Antimony for validation
        antimony.clearPreviousLoads()
        result = antimony.loadSBMLFile(str(sbml_path))
        if result == -1:
            raise ValueError(
                f"Failed to load SBML: {antimony.getLastError()}"
            )
        set_phase("original_antimony_export")
        antimony_text = antimony.getAntimonyString()

        # Write to temp file for validation
        set_phase("original_antimony_write")
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".ant", delete=False
        ) as tmp:
            tmp.write(antimony_text)
            original_ant_path = tmp.name

        try:
            # Determine which tests to run
            if numerical_only:
                run_sym, run_num, run_traj = False, True, False
            elif symbolic_only:
                run_sym, run_num, run_traj = True, False, False
            else:
                run_sym, run_num, run_traj = True, True, True

            set_phase("validator_setup")
            report = validate_recast_pair(
                original_ant_path,
                str(recast_path),
                mode=mode,
                parser="sbml",
                run_symbolic=run_sym,
                run_numerical=run_num,
                run_trajectory=run_traj,
                use_jax=use_jax,
                progress_callback=set_phase,
            )
            set_phase("completed")
            return report.to_dict()
        finally:
            # Clean up temp file
            Path(original_ant_path).unlink(missing_ok=True)

    except Exception as e:
        message = str(e)
        reason = _wrapper_failure_reason(message)
        if reason == "validation_worker_failed":
            reason = "input_load_failed"
        return _validation_failure_report(
            model_id=model_id,
            mode=mode,
            original_file=str(sbml_path),
            recast_file=str(recast_path),
            details=message,
            symbolic_only=symbolic_only,
            numerical_only=numerical_only,
            use_jax=use_jax,
            reason=reason,
            phase=phase_state["current"],
        )


def save_validation_report(
    model_id: str, mode: str, report: dict, test_type: str = "numerical"
):
    """
    Save validation report to JSON with stage-specific filename.

    Args:
        model_id: Model identifier
        mode: Recast mode ('simplified' or 'canonical')
        report: Validation report dict
        test_type: One of 'numerical', 'numerical_jax', 'symbolic'
    """
    # Use stage-specific filename to avoid overwriting between stages
    output_path = (
        Path(config.VALIDATION_DIR) / f"{model_id}_{mode}_{test_type}.json"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        json.dump(report, f, indent=2)


def format_test_result(report: dict) -> str:
    """Format a short test result summary."""
    if "error" in report:
        return f"ERROR: {report['error'][:50]}..."

    tests = report.get("tests", {})

    sym_test = tests.get("symbolic")
    num_test = tests.get("numerical")
    traj_test = tests.get("trajectory")

    symbolic = sym_test.get("result", "?") if sym_test else "-"
    numerical = num_test.get("result", "?") if num_test else "-"
    trajectory = traj_test.get("result", "?") if traj_test else "-"

    failed_results = {"fail", "failed"}
    s = "✓" if symbolic == "pass" else ("✗" if symbolic in failed_results else "-")
    n = "✓" if numerical == "pass" else ("✗" if numerical in failed_results else "-")
    t = "✓" if trajectory == "pass" else ("✗" if trajectory in failed_results else "-")

    return f"sym:{s} num:{n} traj:{t}"


def _subprocess_validate_entry(
    result_queue,
    phase_queue,
    model_id: str,
    sbml_path: str,
    recast_path: str,
    mode: str,
    symbolic_only: bool,
    numerical_only: bool,
    use_jax: bool,
) -> None:
    """Process entry point for isolated validation."""
    try:
        report = validate_model(
            model_id,
            Path(sbml_path),
            Path(recast_path),
            mode,
            symbolic_only,
            numerical_only,
            use_jax,
            phase_queue,
        )
        result_queue.put(("success", report))
    except Exception as e:
        result_queue.put(("error", str(e)))


def _subprocess_validate(args_tuple):
    """
    Run validation in a subprocess (for reliable timeout of SymPy).

    This function runs in a separate process to allow hard kills
    when SymPy hangs during symbolic simplification.
    """
    (model_id, sbml_path, recast_path, mode,
     symbolic_only, numerical_only, use_jax, timeout) = args_tuple

    result_queue = mp.Queue()
    phase_queue = mp.Queue()
    p = mp.Process(
        target=_subprocess_validate_entry,
        args=(
            result_queue,
            phase_queue,
            model_id,
            str(sbml_path),
            str(recast_path),
            mode,
            symbolic_only,
            numerical_only,
            use_jax,
        ),
    )
    p.start()

    queued_result = None
    deadline = time.monotonic() + timeout
    while True:
        try:
            queued_result = result_queue.get_nowait()
            break
        except queue.Empty:
            pass
        except Exception:
            break

        if not p.is_alive():
            break

        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        p.join(timeout=min(0.1, remaining))

    if queued_result is not None:
        if p.is_alive():
            p.join(timeout=2)
            if p.is_alive():
                p.terminate()
                p.join(timeout=2)
            if p.is_alive():
                p.kill()
                p.join()
        status, result = queued_result
        phase, phase_history = _drain_phase_updates(phase_queue)
        if status == "success":
            return _attach_validation_timing_metadata(
                result,
                phase=phase or "completed",
                phase_history=phase_history,
                timeout_seconds=timeout,
            )
        return _validation_failure_report(
            model_id=model_id,
            mode=mode,
            original_file=str(sbml_path),
            recast_file=str(recast_path),
            details=result,
            symbolic_only=symbolic_only,
            numerical_only=numerical_only,
            use_jax=use_jax,
            reason=_wrapper_failure_reason(result),
            phase=phase or "worker",
            phase_history=phase_history,
        )

    if p.is_alive():
        phase, phase_history = _drain_phase_updates(phase_queue)
        # Force kill the subprocess
        p.terminate()
        p.join(timeout=2)
        if p.is_alive():
            p.kill()  # SIGKILL as last resort
            p.join()
        return _validation_failure_report(
            model_id=model_id,
            mode=mode,
            original_file=str(sbml_path),
            recast_file=str(recast_path),
            details=f"Timeout after {timeout}s (subprocess killed)",
            symbolic_only=symbolic_only,
            numerical_only=numerical_only,
            use_jax=use_jax,
            overall_result="timeout",
            reason="validator_timeout",
            timeout_seconds=timeout,
            phase=phase or "subprocess_start",
            phase_history=phase_history,
        )

    try:
        status, result = result_queue.get_nowait()
        if status == "success":
            phase, phase_history = _drain_phase_updates(phase_queue)
            return _attach_validation_timing_metadata(
                result,
                phase=phase or "completed",
                phase_history=phase_history,
                timeout_seconds=timeout,
            )
        else:
            phase, phase_history = _drain_phase_updates(phase_queue)
            return _validation_failure_report(
                model_id=model_id,
                mode=mode,
                original_file=str(sbml_path),
                recast_file=str(recast_path),
                details=result,
                symbolic_only=symbolic_only,
                numerical_only=numerical_only,
                use_jax=use_jax,
                reason=_wrapper_failure_reason(result),
                phase=phase or "worker",
                phase_history=phase_history,
            )
    except Exception:
        phase, phase_history = _drain_phase_updates(phase_queue)
        return _validation_failure_report(
            model_id=model_id,
            mode=mode,
            original_file=str(sbml_path),
            recast_file=str(recast_path),
            details="Subprocess communication failed",
            symbolic_only=symbolic_only,
            numerical_only=numerical_only,
            use_jax=use_jax,
            reason="validator_subprocess_failed",
            phase=phase or "subprocess_communication",
            phase_history=phase_history,
        )


def _parallel_validate_worker(args):
    """Worker function for parallel validation."""
    # Suppress NumPy warnings in worker process
    import warnings
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    np.seterr(invalid="ignore", divide="ignore")

    (model_id, sbml_path, recast_path, mode,
     symbolic_only, numerical_only, use_jax, timeout, use_subprocess) = args

    if use_subprocess:
        report = _subprocess_validate((
            model_id, sbml_path, recast_path, mode,
            symbolic_only, numerical_only, use_jax, timeout
        ))
    else:
        # Use thread-based timeout (may not work for SymPy hangs)
        success, report, error = utils.safe_execute(
            validate_model,
            model_id, sbml_path, recast_path, mode,
            symbolic_only, numerical_only, use_jax,
            timeout_sec=timeout,
            default=None
        )

        if not success or report is None:
            error_msg = error if error else f"Timeout after {timeout}s"
            report = _validation_failure_report(
                model_id=model_id,
                mode=mode,
                original_file=str(sbml_path),
                recast_file=str(recast_path),
                details=error_msg,
                symbolic_only=symbolic_only,
                numerical_only=numerical_only,
                use_jax=use_jax,
                overall_result=(
                    "timeout" if "timeout" in error_msg.lower() else "failed"
                ),
                reason=_wrapper_failure_reason(error_msg),
                timeout_seconds=timeout if "timeout" in error_msg.lower() else None,
                phase="worker",
            )

    return model_id, report


def main():
    """Main execution."""
    parser = argparse.ArgumentParser(
        description="Validate existing recasts against original SBML files"
    )
    parser.add_argument(
        "--mode",
        type=str,
        choices=["simplified", "canonical"],
        default="simplified",
        help="Recast mode to validate",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Limit number of models to validate (for testing)"
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip models that already have validation reports"
    )
    parser.add_argument(
        "--symbolic-only",
        action="store_true",
        help="Only run symbolic validation (can hang on complex models)"
    )
    parser.add_argument(
        "--numerical-only",
        action="store_true",
        help="Only run numerical validation (fast, no symbolic simplification)"
    )
    parser.add_argument(
        "--use-jax",
        action="store_true",
        help="Use JAX autodiff for numerical validation (faster)"
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=60,
        help="Timeout per model in seconds (default: 60)"
    )
    parser.add_argument(
        "--passed-only",
        action="store_true",
        help="Only validate models that passed numerical validation (for stage 2+3)"
    )
    parser.add_argument(
        "--subprocess",
        action="store_true",
        help="Run each validation in subprocess (reliable timeout for SymPy hangs)"
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of parallel workers (-1 for all CPUs, default: 1)"
    )

    args = parser.parse_args()

    # Set up logging
    utils.setup_logging(config.LOG_LEVEL, config.LOG_FILE)

    logger.info("=" * 60)
    logger.info("BioModels Validation Script")
    logger.info("=" * 60)
    logger.info(f"Mode: {args.mode}")
    logger.info(f"Symbolic only: {args.symbolic_only}")
    logger.info(f"Numerical only: {args.numerical_only}")
    logger.info(f"Use JAX: {args.use_jax}")
    logger.info(f"Timeout: {args.timeout}s")
    logger.info(f"Resume: {args.resume}")
    logger.info(f"Passed only: {args.passed_only}")
    logger.info(f"Subprocess isolation: {args.subprocess}")
    logger.info(f"Workers: {args.workers}")

    # Find recast files
    pairs = find_recast_files(args.mode)

    if not pairs:
        logger.error("No recast files found")
        return

    logger.info(f"Found {len(pairs)} recast files to validate")

    # Apply limit if specified
    if args.limit:
        pairs = pairs[:args.limit]
        logger.info(f"Limited to first {args.limit} models")

    # Filter to passed models if requested (for stage 2+3 validation)
    if args.passed_only:
        original_count = len(pairs)
        pairs = filter_passed_models(pairs, args.mode)
        logger.info(
            f"Filtered to {len(pairs)} passed models (from {original_count})"
        )

    # Filter out already validated if resuming
    if args.resume:
        filtered = []
        for model_id, sbml_path, recast_path in pairs:
            val_path = (
                Path(config.VALIDATION_DIR) / f"{model_id}_{args.mode}_validation.json"
            )
            if not val_path.exists():
                filtered.append((model_id, sbml_path, recast_path))
        skipped = len(pairs) - len(filtered)
        pairs = filtered
        if skipped > 0:
            logger.info(f"Skipped {skipped} already validated models")

    if not pairs:
        logger.info("Nothing to validate")
        return

    # Determine number of workers
    n_workers = args.workers
    if n_workers == -1:
        n_workers = os.cpu_count() or 1

    # Determine test_type for file naming (avoid overwriting between stages)
    if args.symbolic_only:
        test_type = "symbolic"
    elif args.use_jax:
        test_type = "numerical_jax"
    else:
        test_type = "numerical"

    logger.info(f"Test type: {test_type}")

    # Validate each model with progress indicators
    pass_count = 0
    fail_count = 0
    error_count = 0

    print(f"\nValidating {len(pairs)} models with {n_workers} workers...\n")
    print("-" * 70)

    if n_workers > 1:
        # Parallel execution
        from joblib import Parallel, delayed

        # Prepare arguments for parallel workers
        work_items = [
            (model_id, str(sbml_path), str(recast_path), args.mode,
             args.symbolic_only, args.numerical_only, args.use_jax,
             args.timeout, args.subprocess)
            for model_id, sbml_path, recast_path in pairs
        ]

        parallel_kwargs = {"n_jobs": n_workers, "verbose": 10}
        if args.subprocess:
            # Subprocess isolation already provides process-level execution and
            # hard timeout behavior. Use threads here to avoid nesting loky
            # process pools around multiprocessing.Process children.
            parallel_kwargs["prefer"] = "threads"

        # Run in parallel with progress reporting
        results = Parallel(**parallel_kwargs)(
            delayed(_parallel_validate_worker)(item) for item in work_items
        )

        # Process results
        for model_id, report in results:
            save_validation_report(model_id, args.mode, report, test_type)

            if report.get("overall_pass", False):
                pass_count += 1
            elif _is_wrapper_failure_report(report):
                error_count += 1
            else:
                fail_count += 1
    else:
        # Sequential execution (original behavior)
        for i, (model_id, sbml_path, recast_path) in enumerate(pairs, 1):
            if args.subprocess:
                # Subprocess isolation for reliable timeout
                report = _subprocess_validate((
                    model_id, sbml_path, recast_path, args.mode,
                    args.symbolic_only, args.numerical_only, args.use_jax,
                    args.timeout
                ))
            else:
                # Thread-based timeout (may not work for SymPy)
                success, report, error = utils.safe_execute(
                    validate_model,
                    model_id, sbml_path, recast_path, args.mode,
                    args.symbolic_only, args.numerical_only, args.use_jax,
                    timeout_sec=args.timeout,
                    default=None
                )

                if not success or report is None:
                    error_msg = error if error else f"Timeout after {args.timeout}s"
                    report = _validation_failure_report(
                        model_id=model_id,
                        mode=args.mode,
                        original_file=str(sbml_path),
                        recast_file=str(recast_path),
                        details=error_msg,
                        symbolic_only=args.symbolic_only,
                        numerical_only=args.numerical_only,
                        use_jax=args.use_jax,
                        overall_result=(
                            "timeout" if "timeout" in error_msg.lower() else "failed"
                        ),
                        reason=_wrapper_failure_reason(error_msg),
                        timeout_seconds=(
                            args.timeout if "timeout" in error_msg.lower() else None
                        ),
                        phase="worker",
                    )

            # Save report
            save_validation_report(model_id, args.mode, report, test_type)

            # Update counts
            if report.get("overall_pass", False):
                pass_count += 1
                status = "✓ PASS"
            elif _is_wrapper_failure_report(report):
                error_count += 1
                status = "⚠ ERROR"
            else:
                fail_count += 1
                status = "✗ FAIL"

            # Print progress line
            test_summary = format_test_result(report)
            total = pass_count + fail_count + error_count
            pct = 100 * pass_count / total if total > 0 else 0

            print(
                f"[{i:3d}/{len(pairs)}] {model_id:25s} {status:8s} ({test_summary})"
            )

            # Print running totals every 10 models or at the end
            if i % 10 == 0 or i == len(pairs):
                print(
                    f"         Running: ✓ {pass_count} pass | "
                    f"✗ {fail_count} fail | ⚠ {error_count} error | "
                    f"{pct:.1f}% pass rate"
                )
                print("-" * 70)

    # Final summary
    total = pass_count + fail_count + error_count
    pass_rate = 100 * pass_count / total if total > 0 else 0

    summary = f"""
Validation Summary
==================
Total validated: {total}
Pass: {pass_count} ({pass_rate:.1f}%)
Fail: {fail_count}
Error: {error_count}
"""

    print(summary)

    # Save summary
    summary_path = Path(config.RESULTS_DIR) / "validation_summary.txt"
    with open(summary_path, "w") as f:
        f.write(summary)

    logger.info(f"Saved summary to {summary_path}")
    logger.info("\nValidation complete!")


if __name__ == "__main__":
    main()
